version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8088:80"
    restart: always
    depends_on:
      - php-fpm
      - db
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  php-fpm:
    build: docker
    container_name: php-fpm
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/conf/php/php.ini:/usr/local/etc/php/php.ini
      - composer-cache:/root/.composer/cache
    env_file:
      - .env
    environment:
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      PHP_POST_MAX_SIZE: "100M"
      PHP_MEMORY_LIMIT: "256M"
      PHP_MAX_EXECUTION_TIME: "300"
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33066:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
      image: rabbitmq:3-management    # Официальный образ RabbitMQ с панелью управления
      hostname: rabbitmq              # Имя хоста для контейнера
      restart: always                 # Автоматический перезапуск при сбое
      environment:
          # Настройки пользователя и пароля через переменные окружения
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}        # Если RABBITMQ_USER не задан, используется guest
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}    # Если RABBITMQ_PASSWORD не задан, используется guest
          - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST:-/}         # Виртуальный хост, по умолчанию "/"
      ports:
          - "5672:5672"   # Порт для AMQP протокола (основной порт для работы с очередями)
          - "15672:15672" # Порт для веб-интерфейса управления
      volumes:
          - ./docker/rabbitmq/data:/var/lib/rabbitmq    # Хранение данных
          - ./docker/rabbitmq/logs:/var/log/rabbitmq    # Хранение логов

volumes:
  composer-cache:
